// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBATx0UoQbX6K1gyiqdCZ36nozgDPGoLRc',
    appId: '1:248834245791:web:af727fe7d9839101514eaa',
    messagingSenderId: '248834245791',
    projectId: 'instagram-clone-7139d',
    authDomain: 'instagram-clone-7139d.firebaseapp.com',
    storageBucket: 'instagram-clone-7139d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Q4hzPL6xGvaSzfyJj5GJr0S3RypmfCg',
    appId: '1:248834245791:android:3c6decb9ef59fe9c514eaa',
    messagingSenderId: '248834245791',
    projectId: 'instagram-clone-7139d',
    storageBucket: 'instagram-clone-7139d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9hTh2PamW7lbl5Ha8rszxuryuFjSuwAk',
    appId: '1:248834245791:ios:748ccd26ff5393d5514eaa',
    messagingSenderId: '248834245791',
    projectId: 'instagram-clone-7139d',
    storageBucket: 'instagram-clone-7139d.appspot.com',
    iosBundleId: 'com.instagramclone.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBATx0UoQbX6K1gyiqdCZ36nozgDPGoLRc',
    appId: '1:248834245791:web:d235e0db797e687b514eaa',
    messagingSenderId: '248834245791',
    projectId: 'instagram-clone-7139d',
    authDomain: 'instagram-clone-7139d.firebaseapp.com',
    storageBucket: 'instagram-clone-7139d.appspot.com',
  );
}
